# Generated by Django 4.1.2 on 2022-11-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
    ]
