# Generated by Django 4.1.2 on 2022-11-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20221116_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
