# Generated by Django 4.1.2 on 2022-11-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_creator_alter_chatmember_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='title',
        ),
    ]
