# Generated by Django 4.1.2 on 2022-11-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_name_chat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmember',
            name='is_creator',
        ),
    ]
